spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bankingdb
    username: ${DB_USERNAME:dbadmin}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your-secret-key-should-be-very-long-and-secure}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.example.banking: INFO
    org.springframework: WARN